### PR TITLE
Editpage

### PR DESCRIPTION
**Pull request by rkoonireddy**
I created the view page styling and log out redirect. Yet to implement. The Editing user with API part.

### CODE REVIEW

**Comment by Danielgergely** [comment]
2 observations:
  - When using styled-components, it makes sense to name the variables "StyledXXX". Then we know that we are not talking about a standard react components, but a styled one. I would recommend changing this.
  - You can also use some of the components I created in the Login/Register page. (Buttons, form fields). Most of them are exported and can directly be used in other files, but if you need one, just put "export" in front of the styled component. This can keep our design uniform throughout the application. (Of course this is optional)

**Comment by Danielgergely** [comment]
One other thing. We are using a develop branch, so please create a request to merge into the develop branch. We can then merge develop into main once we have a major release

**Comment by rkoonireddy** [comment]
I pushed into develop branch directly. That was stupid, I will be more careful next one onwards. Right now everything works from a functionality perspective.

**Comment by krwro** [comment]
Also, make sure to add a reference to the issue when naming a branch or writing the commit message so we know which issue it belongs to/implements. You can do this by including the issue ID in the name of the commit message/branch. E.g., SCRUM-1 Add xy

**Pull request closed without merging**
